### ISSUE TITLE
Update to latest (unstable) version of accelerate 

### ISSUE THREAD

**Issue by yongqli** [ekmett/linear-accelerate#3]
There's been some changes to how accelerate represents types. I've started some very preliminary work on updating `linear-accelerate`. See https://github.com/AccelerateHS/accelerate/issues/210#issuecomment-77162070

**Comment by tmcdonell** [comment]
[linear-accelerate-0.3](http://hackage.haskell.org/package/linear-accelerate) is now on Hackage.
