### ISSUE TITLE
Cut GHC 8.2-compatible release

### ISSUE THREAD

**Issue by RyanGlScott** [ekmett/linear-accelerate#8]
`linear-accelerate-0.3` doesn't build out of the box with GHC 8.2.1-rc2 due to https://github.com/ekmett/linear-accelerate/pull/6, so we should cut a minor release soon to rectify this. We're almost there, since the HEAD version of `linear-accelerate` builds without issue on 8.2. We just need to update the `.travis.yml` script accordingly to verify this.

**Comment by tmcdonell** [comment]
Uploaded as [linear-accelerate-0.4](http://hackage.haskell.org/package/linear-accelerate-0.4).

(uploaded as a major release due to the fix for `(^-)` and `(-^)` in https://github.com/ekmett/linear-accelerate/commit/08c596e1b32bf62a5394c85997850020c32865a8)
